export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";
export const DRONE_START_FETCH = 'EVENT/DRONE_START_FETCH'
export const DRONE_INFO = 'EVENT/DRONE_INFO';
export const DRONE_CANCEL_FETCH = 'EVENT/DRONE_CANCEL_FETCH';
